# Generated by Django 4.0.2 on 2022-06-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myonlinecv', '0002_alter_codingskill_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='source_code',
            field=models.TextField(default='#'),
        ),
        migrations.AlterField(
            model_name='project',
            name='media',
            field=models.ImageField(upload_to='projects/'),
        ),
    ]
