# Generated by Django 4.0.2 on 2022-06-18 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myonlinecv', '0003_project_source_code_alter_project_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='media',
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myonlinecv.project')),
            ],
        ),
    ]
