# Generated by Django 4.0.2 on 2022-06-18 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myonlinecv', '0004_remove_project_media_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
