# Generated by Django 4.0.2 on 2022-06-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myonlinecv', '0006_alter_image_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default=None, upload_to='projects/'),
        ),
    ]
