# Generated by Django 4.0.2 on 2022-06-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myonlinecv', '0008_alter_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(default=None, upload_to='projects/'),
        ),
    ]
