# Generated by Django 4.0.2 on 2022-06-21 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myonlinecv', '0010_programminglanguage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programminglanguage',
            name='timestamp',
        ),
    ]
