# Generated by Django 4.0.2 on 2022-06-21 14:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myonlinecv', '0011_remove_programminglanguage_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='programminglanguage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 6, 21, 14, 11, 56, 884034, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
