# Generated by Django 4.0.2 on 2022-06-22 08:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myonlinecv', '0012_programminglanguage_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='timestamp',
            field=models.DateField(default=datetime.datetime(2022, 6, 22, 8, 50, 16, 490828, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
